UP=0
DOWN=1
LEFT=2
RIGHT=3
DIRECTIONS = [UP, DOWN, LEFT, RIGHT]
KEY_TO_DIRECTION = {
    # Arrow Keys
    59432: UP,
    59440: DOWN,
    59435: LEFT,
    59437: RIGHT,
    # wasd
    119: UP,
    115: DOWN,
    97: LEFT,
    100: RIGHT,
    # WASD
    87: UP,
    83: DOWN,
    65: LEFT,
    68: RIGHT
}

BLOCK_AIR = 0
BLOCK_WALL = 1
BLOCK_EXIT = 2
BLOCK_PLAYER = 3
BLOCK_VEIW_BUSTER = 4
BLOCK_BORDER = -1
BLOCK_KEY = 100
BLOCK_GATE = 200

BLOCKS_KEYS = (100, 199)
BLOCKS_GATES = (200, 299)

BLOCKING_BLOCKS = [BLOCK_WALL, BLOCK_BORDER]

LOADER_SYMBOLS = {
    ' ': BLOCK_AIR,
    '$': BLOCK_WALL,
    'P': BLOCK_PLAYER,
    'E': BLOCK_EXIT,
    'K': BLOCK_KEY,
    'G': BLOCK_GATE,
    '+': BLOCK_VEIW_BUSTER
}

SCREEN_WIDTH = 100
SCREEN_PADDING = 10
SCREEN_ITEM_WIDTH = SCREEN_WIDTH - SCREEN_PADDING * 2
